### ISSUE TITLE
Make result update more efficient

### ISSUE THREAD

**Issue by jzaefferer** [jquery/testswarm#215]
On big job pages the update is rather slow. As @Krinkle said in #213:

"It does create a document fragment, though, that should be made more efficient by only returning the table html from the server. That way we don't have to have `.load()` it and `.find()` the table in order to compare the innerHTML."

Should do that.

**Comment by Krinkle** [comment]
Resolved with:

* 979693b8466247018eb880e7b744c24faf7d911e `job.js: Use $targetTable instead of querying the DOM again`
* aca18054abb693a214d4e697e8bce0cf605049bc `job.js should keep refreshing even when everything is complete and "reset" happens.`
* 86cb636d605cb0bcbfbd044119a06f067827709f `job.js: Add error handler to hide indicator and schedule next update`

And today:

* a569c99a19665682fb94781073c1d12798b14d48  `Page: Implement partial response support for JobPage`
