### ISSUE TITLE
The Android icon looks weird

### ISSUE THREAD

**Issue by mgol** [jquery/testswarm#306]
Open http://swarm.jquery.org/project/jqueryperiodic. The Android icon is as follows:
![screen shot 2015-07-16 at 19 56 51](https://cloud.githubusercontent.com/assets/1758366/8731027/e33cbbc2-2bf4-11e5-8332-3e97b40e8c16.png)
instead of just:
![the robot icon](http://swarm.jquery.org/img/os-android.png)
The actual icon is actually two ones - the first is:
![browser-unknown](http://swarm.jquery.org/img/browser-unknown.png)
and, set as a background for the `::after` pseudo-element is the Android icon. This is set as https://github.com/jquery/testswarm/blob/ba50f43b13c8be3b72bf499f33b81692d15e2942/css/testswarm.css#L476-L478

It seems to me that the browser is not recognized so the image is just "an unknown browser under Android"; is that true? For Android <4.4 the Android browser should just have its own icon. For >=4.4 the Chrome icon could appear as that's what we're testing here. But a regular robot icon would still be fine, I guess since BrowserStack presents it just as an Android 4.4/5.0 Browser and not as Chrome.

**Comment by Krinkle** [comment]
This is because the swarm.jquery.org configuration uses a user-agent match that only looks for the OS family, not any particular browser.

I've added icons for the Android and Chrome Mobile browsers. They will be used on the home page once we update our configuration to specify the "Android" and "Chrome Mobile" browserFamily accordingly.

**Comment by Krinkle** [comment]
Hm..  it may not be that simple. It's not browser "Android" for Android 2.3 and browser "Chrome Mobile" for Android 4 and higher.

Using http://swarm.jquery.org/job/929 as example, we see the following user agents / ua-parser data:

* Android 2.3 – http://swarm.jquery.org/result/472803 – http://swarm.jquery.org/client/65156 – "Android 2.3.3 / Android 2.3.3"
* Android 4.0 – http://swarm.jquery.org/result/472805 – http://swarm.jquery.org/client/65189 – "Android 4.0.3 / Android 4.0.3"
* Android 4.1 – http://swarm.jquery.org/result/472801 – http://swarm.jquery.org/client/65188 – "Android 4.1.2 / Android 4.1.2"
• Android 4.2 – http://swarm.jquery.org/result/472787 – http://swarm.jquery.org/client/65184 – "Android 4.2.2 / Android 4.2.2"
* Android 4.3 – http://swarm.jquery.org/result/472721 – http://swarm.jquery.org/client/65155 – "Android 4.3 / Android 4.3"
* Android 4.4 – http://swarm.jquery.org/result/472758 – http://swarm.jquery.org/client/65183 – "Chrome 30.0.0 / Android 4.4.2" (**Not "Chrome Mobile", but "Chrome")
* Android 5.0 – http://swarm.jquery.org/result/472711 – http://swarm.jquery.org/client/65170 – "Chrome 37.0.0 / Android 5.0" (**Not "Chrome Mobile", but "Chrome")

**Comment by mzgol** [comment]
The Chrome icon should be fine, I guess, if only we see info about the Android version in TestSwarm as well.

BTW, this should only concern Android 4.4 or newer, Android 4.0-4.3 uses the default Android Browser that was removed in 4.4.

I have doubts if it makes sense to test Android versions for Android >= 5.0 since they just use Chrome Mobile and that matters, not the Android version used. Unfortunately, that's what we currently get from BrowserStack. Android 4.4 is an odd one since it has Chrome as a default browser but it's WebView has a frozen Chromium version. In Android 5.0+ both auto-update.

**Comment by Krinkle** [comment]
There's another problem I forgot about. The BrowserStack API doesn't provide browser property for mobile devices. Adding a browserFamily to these would mean the tests no longer get run.

I've reverted the jquery/infrastructure patch that added it for Android 2.3 because it was building up a backlog of unrun runs.

**Comment by mzgol** [comment]
The [Browserstack API](https://api.browserstack.com/4/browsers) has a `browser` field for mobile browsers; for the Android one it's `"Android Browser"`. OTH, it returns `"Android Browser"` even for Android >= 4.4 which seems incorrect.

**Comment by Krinkle** [comment]
Aha, so we can use it but will need a mapping in testswarm-browserstack since ua-parser calls it `browserFamily=Android` and BrowserStack uses `browser=Android Browser`.

**Comment by Krinkle** [comment]
So... adding that mapping didn't work. testswarm-browserstack is still unable to map the browser.

This is because testswarm-browserstack explicitly ignores the `browser.browser` property from BrowserStack (see [testswarm-browserstack.js#L323-L330](https://github.com/clarkbox/testswarm-browserstack/blob/1b22aca35a63a8ea709a493c1937d86f19b9b9cc/src/testswarm-browserstack.js#L323-L330)) due to an inconsistency in the API between `/workers` and `/browsers`.

`/browsers` lists `browser: "Android Browser"`, but `/worker` doesn't accept that property.

**Comment by Krinkle** [comment]
This is now fixed.

* jquery/testswarm: The UA-parser refers to the Android browser as "Android", but BrowserStack refers to it as "Android Browser".  Fixed in https://github.com/clarkbox/testswarm-browserstack/commit/6be074a0a5c91648e7338fefa47f86131ecc81e0.
* browserstack/api: BrowserStack API v3 had a bug where the `/browsers` endpoint exposed a browser name, but `/workers` did not support spawning a mobile browser by browser name, only by OS and device. Fixed upstream in BrowserStack v4.
* testswarm-browserstack: Updated to use API v4 by @mgol in https://github.com/clarkbox/testswarm-browserstack/commit/846a55e3b5b7e0dc2cd96b39f31411369cfed212.
* testswarm-browserstack: Removed hack for absence of `.browser` in v3 worker objects so that we can start using the v4 model, in https://github.com/clarkbox/testswarm-browserstack/commit/31044fbb553a50f6c85ba6929898650be01a4667.
* jquery/infrastructure config: Added `browserFamily: Android` to the android user agent configs for our swarm, in https://github.com/jquery/infrastructure/commit/553ac20746c09e7e586b34ce22f72154fe9b5f24.

**Comment by Krinkle** [comment]
Per https://github.com/clarkbox/testswarm-browserstack/commit/f246bb8163d663ca173ae3be386a9f7bb82fd66c and https://github.com/jquery/infrastructure/commit/953ccd7b7e08db1fd5db5aa8f68c519be4737f4d, Chrome Mobile on Android 4.4+ now also works properly.
<img width="399" alt="screen shot 2017-03-30 at 12 38 42" src="https://cloud.githubusercontent.com/assets/156867/24522870/d41dbb64-1545-11e7-9342-d0886ef20914.png">
