### ISSUE TITLE
Edge is recognized as Edge 12

### ISSUE THREAD

**Issue by mzgol** [jquery/testswarm#308]
If I joined the swarm with Microsoft Edge, I see this:
![screen shot 2015-07-16 at 20 19 11](https://cloud.githubusercontent.com/assets/1758366/8731495/0746c9d8-2bf8-11e5-8416-4149eb51545f.png)
I've just added this line to the browser definitions in the infrastructure repo:
```js
"edge": {
	"browserFamily": "Edge"
},
```
without specifying `browserMajor` as Edge has no version numbers. It'd be best to either drop the number or, if something has to be there, to pass the build number instead - which is most likely detected as a `browserMinor` since it's in the User Agent after `12` and a dot. The `12` part is meaningless and not part of any official version number.

See e.g. the discussion from https://github.com/jquery/contribute.jquery.org/issues/95#issuecomment-117856894 going forward.

**Comment by Krinkle** [comment]
I'm not sure I see the problem. This screenshot is of the run page. The run page shows the full browser and os name and version as recognised by ua-parser. It is not used for anything other than showing you what the current browser is (and in the test results).

It is not used for fragmenting job page columns and does not affect distribution of test runs to clients. For that, only the specified userAgent descriptor is used, which in your case is unified for all of "Edge".

For example, matching `{ browserFamily: Chrome, browserMajor: 46 }` will result in a column "Chrome 45" but the results will document e.g. "Chrome 46.0.2455.0 / Mac OS X 10.10.4". It's a one-to-many relationship.

If the issue is that the label itself uses "12.0" as a version and doesn't show the build number, that's up to upstream ua-parser, but doesn't affect us in any way.

TestSwarm does actually display the minor and patch versions if they are available. And ua-parser supports that as well for Edge. E.g. user agent `Edge/12.9600` shows "Edge 12.9600 / Windows 10". It isn't generalised as 12.0 in TestSwarm nor ua-parser.

**Comment by mzgol** [comment]
You're right, I thought the data displayed is the one identified by TestSwarm mappings, not by ua-parser. I've just started a jQuery Core Periodic run and Edge displays without a number as expected: http://swarm.jquery.org/job/937.

I'll close this issue then.

**Comment by jdalton** [comment]
Based the MS Edge [blog guidance](https://blogs.windows.com/msedgedev/2015/09/21/understanding-versions-in-an-evergreen-browser/) for dev-facing features track against the EdgeHTML version rather than the Edge app version.

![example](https://cloud.githubusercontent.com/assets/4303/10007582/5cf75e80-607b-11e5-95a5-7f932332c406.png)

**Comment by mzgol** [comment]
@jdalton This won't work since if we specify a major it has to match what BrowserStack provides. And BrowserStack uses the app version, i.e. `20` currently. Sauce Labs does sth similar btw (but it also specifies the build version as minor which BrowserStack doesn't do).

This is going to get incredibly confusing once the EdgeHTML version reaches 20; I think it will cause problems that the numbers won't match. People will constantly wonder what "Edge 22" really means in a particular comment, display value etc.

**Comment by mzgol** [comment]
BTW, we're currently thinking how to mark Edge workarounds in the code comments in jQuery: https://github.com/jquery/contribute.jquery.org/issues/95#issuecomment-117858785. Do you think to reduce confusion we should write `EdgeHTML 12-13+`, i.e. `EdgeHTML` and not `Edge` to make it clear we're talking about the engine number? In every other case we write the name of the browser and not its engine so it would get inconsistent but otherwise it'd get even more confusing...

**Comment by jdalton** [comment]
I've reached out to sauce labs to adjust their version from `20` to `12`. I'll do a similar thing for BrowserStack.

**Comment by mzgol** [comment]
Oh, if they changed that that would be great! :)

**Comment by jdalton** [comment]
My advice would be to call it `MS Edge 12-13`. I'm hopping now that the blog post is out we can correct the current use so that the whole `20` vs `12` thing will be just a minor confusing note of the past.

I'll and others will continue to push for a more straight forward version representation in the about dialog too.

**Comment by jdalton** [comment]
Btw Sauce is open to changing they just wanted an official doc or blog post to reference so those wheels are in motion.

**Comment by gibson042** [comment]
Based on that blog, `EdgeHTML` seems like the clearest identifier for our Support comments. I actually _prefer_ engine version to browser version, but we don't always dig deep enough to discover the former. And we can always reference the browser itself if we need to (but fingers crossed that we won't).

**Comment by jdalton** [comment]
Tools are being advised to reference `Edge` or `MS Edge` then `12` or `13`. Treat it like any other browser. Getting bogged down with the platform dll name should be avoided.

**Comment by jdalton** [comment]
![image](https://cloud.githubusercontent.com/assets/4303/10008459/a250842c-6083-11e5-9118-ba281ca52add.png)
![image](https://cloud.githubusercontent.com/assets/4303/10008464/b09bf548-6083-11e5-8c52-b444d320a6aa.png)

**Comment by mzgol** [comment]
> I actually prefer engine version to browser version, but we don't always dig deep enough to discover the former.

The engine version isn't always accurate as e.g. various mobile browsers are WebKit- or Blink-based but they often add their own quirks to the engine; one example is Yandex.Browser. Therefore, I think we should mention browsers and not engines as that's as much unambiguous as we can be.

If we add @jdalton's recommendation that all tools should use `Edge` and the engine version then it doesn't seem worth it to diverge, especially that some of them already do that.

We can just ignore the "app version", pretending it doesn't exist.

**Comment by jdalton** [comment]
> We can just ignore the "app version", pretending it doesn't exist.

Yep! That's what I do :see_no_evil:

**Comment by gibson042** [comment]
I'll submit to consensus. But I do think they're setting theirselves up for confusion, since "Edge" corresponds to platform version in User-Agent but app version in the [About screen](http://az648995.vo.msecnd.net/win/2015/09/about.png).

**Comment by mzgol** [comment]
@gibson042 Yes, I'd prefer they didn't do that as I indicated above. But we have what we have.

**Comment by jdalton** [comment]
> But I do think they're setting theirselves up for confusion, since "Edge" corresponds to platform version in User-Agent but app version in the About screen.

Yap, we're working on it. The about dialog will take a bit to clear up.

**Comment by jdalton** [comment]
Should I create a PR to add version info to Edge or can you all tackle it?

**Comment by mzgol** [comment]
@jdalton This is located in our private repo so we'll have to do it ourselves. Thanks for the nudge.

However, first I'd like to wait for BrowserStack to confirm they're going to keep old Edge versions around like they do for Chrome/Firefox and not just keep the latest version (in such a case I'd prefer to not write down the version in our setup as it'll break after an update).

I'd love them to keep older versions, we'd then be able to assert we support current & previous Edge, similarly as we do with older rolling-release browsers. So far we only declare [current version support for Edge](https://github.com/jquery/jquery.com/blob/0d5d2d7d648f81c9e61a75e1c7b87c1d05c75565/pages/browser-support.html#L7-L34). (this is on the [`jquery-3` branch](https://github.com/jquery/jquery.com/tree/jquery-3), to be published the day we release jQuery 3.0.0)
