### ISSUE TITLE
Each browser gets spawned twice

### ISSUE THREAD

**Issue by mgol** [jquery/testswarm#310]
Each job seams to open _two_ BrowserStack connections to each browsers, e.g. my recent restart of the `core` module in Android 4.3 at:
http://swarm.jquery.org/job/979
has opened:
https://www.browserstack.com/automate/builds/9b37aec0af76d776a5e71d29b44f619ebc22766c/sessions/bc9bfc215317298503613192aea9cfa8e8ce3975
and:
https://www.browserstack.com/automate/builds/9b37aec0af76d776a5e71d29b44f619ebc22766c/sessions/779ad68fd61f6e03dfa5422c4263e9dd0f510a59

This effectively decreases our pool of available workers from 30 to 15.

Restarting any job triggers this bug so it's easy to reproduce.

**Comment by Krinkle** [comment]
The spawning happens in [testswarm-browserstack](https://github.com/clarkbox/testswarm-browserstack).

The number of similar workers spawned for the same browser is controlled by the `config.browserstack.eqLimit` property and defaults to `2`. This is by design and very much intentional.

As soon as once browser's neediness is exhausted, available resources will be allocated to the next needed browser.

In general, we prefer fast turnover of individual jobs instead of slow turnover of all jobs at once.

**Comment by mzgol** [comment]
Your description makes sense but I've noticed the two workers are usually spawned at the same time and I didn't notice a speedup because there are two of them instead of one.

In fact, I've noticed a different thing - during a recent periodic run at http://swarm.jquery.org/job/1013 `tween` tests timed out in Android 4.3 and I restarted it before all the other jobs finished. The result was that a lot of Android 4.3s were queued & queued, all other jobs finished, no other Jenkins job was started and yet TestSwarm was waiting for just this one job and yet all 30 workers were busy with more in the queue.

It seems some of the workers that were spawned for other tests (like some Android 4.0 ones) weren't killed and were just waiting for 10 minutes or longer to be killed by BrowserStack itself. This was draining the queue and effectively made the whole Jenkins job take a lot of time to finish.
